title: Bro Valentine
email: eric@grainandmortar.com
description: Valentine's for your Bro's
baseurl: "/brovalentine"
url: "http://ericdowns.github.io"
author: Grain & Mortar
relative_permalinks: false
permalink: /:title/
paginate: 8
paginate_path: "/page:num"

collections:
    valentines:
      output: true
      permalink: /:collection/:path 
      
defaults:
  - scope:
      path: ""
      type: valentines
    values:
      layout: valentines

markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - gulpfile.js
  - package.json
  - bower.json
  - bower_components
